### ISSUE TITLE
How 2 depend

### ISSUE THREAD

**Issue by RoboMWM** [RoboMWM/blah#1]
```
[15:16:58 ERROR]: Error occurred while enabling blah v0.0.1 (Is it up to date?)                                                                                                
java.lang.NullPointerException                                                                                                                                                 
        at me.robomwm.blah.ChatListener.<init>(ChatListener.java:15) ~[?:?]                                                                                                    
        at me.robomwm.blah.Main.onEnable(Main.java:9) ~[?:?]                                                                                                                   
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                                
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                   
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                  
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                       
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                    
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                          
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                          
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                          
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                       
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:561) [paperspigot.jar:git-PaperSpigot-c725b9c-12698ea]                                        
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]                                                                                                                  
```

**Comment by RoboMWM** [comment]
And yes, GriefPrevention loads before my plugin loads.
